export const BOT_TOKEN = 'BOT_TOKEN';
export const BASE_GITLAB_URL = 'BASE_GITLAB_URL';
export const MODE = 'MODE';
export const POSTGRES_HOST = 'POSTGRES_HOST';
export const POSTGRES_PORT = 'POSTGRES_PORT';
export const POSTGRES_USER = 'POSTGRES_USER';
export const POSTGRES_PASSWORD = 'POSTGRES_PASSWORD';
export const POSTGRES_DATABASE = 'POSTGRES_DATABASE';
